server:
  port: 8762
spring:
  application:
    name: zuul-service

eureka:
  client:
      registerWithEureka: true
      fetchRegistry: true
  serviceurl:
      defaultzone: http://localhost:8761/eureka/

management:
  endpoints:
      routes:
        enabled: true
        sensitive: false
      web:
        exposure:
            include: "*"